name: Deploy Next.js on EC2

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15'

      # Install dependencies
      - name: Install Dependencies
        run: npm ci --ignore-scripts

      # Build the Next.js application
      - name: Build Next.js App
        run: npm run build

      # Archive build files
      - name: Archive Next.js Build
        run: tar -czf nextjs-build.tar.gz .next package.json package-lock.json ecosystem.config.js

      # Upload the build as an artifact
      - name: Upload Next.js Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build
          path: nextjs-build.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Download build artifact from previous job
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: nextjs-build

      # Configure SSH for EC2 access
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Deploy to EC2
      - name: Deploy Next.js to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          # Upload tarball to EC2
          scp nextjs-build.tar.gz $EC2_USER@$EC2_HOST:~/nextjs-build.tar.gz

          # SSH into EC2 and deploy
          ssh $EC2_USER@$EC2_HOST << 'EOF'
            # Clean up old app and extract new build
            rm -rf ~/nextjs-app && mkdir -p ~/nextjs-app
            tar -xzf ~/nextjs-build.tar.gz -C ~/nextjs-app

            # Install production dependencies
            cd ~/nextjs-app
            npm ci --only=production

            # Start the Next.js app using PM2
            pm2 delete nextjs-app || true
            pm2 start npm --name nextjs-app -- start
          EOF
