name: Deploy React on EC2

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15'

      # Install dependencies
      - name: Install Dependencies
        run: npm ci --ignore-scripts

      # Build the production version of the app
      - name: Build React App
        run: npm run build

      # Archive build files to prepare for deployment
      - name: Archive Build
        run: tar -czf react-build.tar.gz build package.json package-lock.json

      # Upload the build as an artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: react-build.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Download build artifact from previous job
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: react-build

      # Configure SSH for EC2 access
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Deploy to EC2
      - name: Deploy React to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          # Upload tarball to EC2
          scp react-build.tar.gz $EC2_USER@$EC2_HOST:~/react-build.tar.gz

          # SSH into EC2 and deploy
          ssh $EC2_USER@$EC2_HOST << 'EOF'
            # Clean up old app and extract new build files
            rm -rf ~/react-app && mkdir -p ~/react-app
            tar -xzf ~/react-build.tar.gz -C ~/react-app

            # Serve the React app using Nginx (adjust the configuration as needed)
            cp ~/react-app/build/* /var/www/html/

            # Restart Nginx to serve the new React app
            sudo systemctl restart nginx
          EOF
