name: Deploy Next.js Website to EC2

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Checkout the repository code

      - name: Set up Node.js for Next.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15' # Use the specified Node.js version

      - name: Install Dependencies for Website
        run: npm install --frozen-lockfile # Install all dependencies from package-lock.json

      - name: Build Next.js Website
        run: npm run build # Build the Next.js project

  deploy:
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job

    steps:
      - uses: actions/checkout@v3 # Checkout the repository code again for deployment

      - name: Set up Node.js for Next.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15'

      - name: Install Dependencies for Website
        run: npm install --frozen-lockfile # Install all dependencies

      - name: Build Next.js Website
        run: npm run build # Ensure the project is built before deployment

      # Configure SSH access to the EC2 instance
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }} # SSH key for access
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Deploy the website to EC2
      - name: Deploy Next.js Website to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh $EC2_USER@$EC2_HOST "mkdir -p ~/applications/website"  # Create the 'website' folder on EC2

          rsync -avz \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='.github' \
            . $EC2_USER@$EC2_HOST:~/applications/website/

          # Install production dependencies on EC2 for the website
          ssh $EC2_USER@$EC2_HOST "cd ~/applications/website && npm install --frozen-lockfile --production"

          # (Optional) Build the frontend for production (if applicable)
          ssh $EC2_USER@$EC2_HOST "cd ~/applications/website && npm run build"

          # Start Next.js app using PM2 (or a custom process manager)
          ssh $EC2_USER@$EC2_HOST "pm2 start 'npm run start' --name nextjs-website"
